-- .luacheckrc
std = "max"

globals = {
    "OpenItDB",
    "CreateFrame",
    "UIParent",
    "C_Container",
    "C_Item",
    "C_TooltipInfo",
    "C_ToyBox",
    "C_QuestLog",
    "C_CurrencyInfo",
    "Settings",
    "InCombatLockdown",
    "IsShiftKeyDown",
    "GameTooltip",
    "GameTooltip_Hide",
    "SlashCmdList",
    "SLASH_OPENIT1",
    "Enum",
    "time",
    "pairs",
    "ipairs",
    "table",
    "math",
    "print",
    "_G",
    "ITEM_OPENABLE",
    "ITEM_SPELL_TRIGGER_ONUSE",
    "tonumber",
    "tostring",
    "ITEM_QUALITY_COLORS",
    "PlaySound",
    "SOUNDKIT",
}
